# Generated by Django 4.2 on 2023-04-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidi', models.IntegerField()),
                ('assignmentmi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='departmentsem8assignmentsubnames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentsub1', models.CharField(max_length=90)),
                ('assignmentsub2', models.CharField(max_length=90)),
                ('assignmentsub3', models.CharField(max_length=90)),
                ('assignmentsub4', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='departmentsem8assignmentuploadmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('assignmentm1', models.IntegerField()),
                ('assignmentm2', models.IntegerField()),
                ('assignmentm3', models.IntegerField()),
                ('assignmentm4', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='departmentsem8markupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('suba', models.IntegerField()),
                ('subb', models.IntegerField()),
                ('subc', models.IntegerField()),
                ('subd', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='departmentsem8subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('sub1', models.CharField(max_length=100)),
                ('sub2', models.CharField(max_length=100)),
                ('sub3', models.CharField(max_length=100)),
                ('sub4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='staffregistrationmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(max_length=30)),
                ('staffeid', models.EmailField(max_length=254)),
                ('staffpassword', models.CharField(max_length=40)),
                ('staffconfirmationps', models.CharField(max_length=40)),
                ('classteacherbatch', models.CharField(max_length=90)),
                ('staffsemeter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='studentregistrationmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=30)),
                ('studentrollno', models.CharField(max_length=30)),
                ('studentimage', models.ImageField(upload_to='')),
                ('studentdeparment', models.CharField(max_length=30)),
                ('studentdob', models.DateField()),
                ('studentbatch', models.CharField(max_length=30)),
                ('studentsemester', models.CharField(max_length=30)),
                ('studentpassword', models.CharField(max_length=30)),
                ('studentemail', models.EmailField(max_length=254)),
                ('studentclassteacher', models.CharField(max_length=50)),
            ],
        ),
    ]
