# Generated by Django 4.2 on 2023-04-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0002_semsubjectuploadother'),
    ]

    operations = [
        migrations.CreateModel(
            name='semsubjectsuploadother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subo1', models.CharField(max_length=80)),
                ('subo2', models.CharField(max_length=80)),
                ('subo3', models.CharField(max_length=80)),
                ('subo4', models.CharField(max_length=80)),
                ('subo5', models.CharField(max_length=80)),
                ('subo6', models.CharField(max_length=80)),
                ('semestero', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='semsubjectuploadother',
        ),
    ]
