# Generated by Django 4.1 on 2023-04-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0004_alter_studentregistrationmodel_studentimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentsem8assignmentuploadmodel',
            old_name='sid',
            new_name='semester',
        ),
    ]
