# Generated by Django 4.1 on 2023-04-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0005_rename_sid_departmentsem8assignmentuploadmodel_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentsem8assignmentuploadmodel',
            old_name='semester',
            new_name='sid',
        ),
    ]
