# Generated by Django 4.1 on 2023-04-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0007_stusernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachernotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('tnottime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
