# Generated by Django 4.1 on 2023-04-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0008_teachernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='departmentsemassignmentsubnames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
                ('assgsub1', models.CharField(max_length=90)),
                ('assgsub2', models.CharField(max_length=90)),
                ('assgsub3', models.CharField(max_length=90)),
                ('assgsub4', models.CharField(max_length=90)),
            ],
        ),
    ]
