# Generated by Django 4.1 on 2023-04-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0009_departmentsemassignmentsubnames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='departmentsem8assignmentsubnames',
        ),
    ]
