# Generated by Django 4.1 on 2023-05-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0010_delete_departmentsem8assignmentsubnames'),
    ]

    operations = [
        migrations.CreateModel(
            name='departmentsemmarkupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('suba', models.IntegerField()),
                ('subb', models.IntegerField()),
                ('subc', models.IntegerField()),
                ('subd', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='departmentsem8markupload',
        ),
    ]
