# Generated by Django 4.1 on 2023-05-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0011_departmentsemmarkupload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='internals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp1', models.IntegerField()),
                ('pp2', models.IntegerField()),
                ('pp3', models.IntegerField()),
                ('pp4', models.IntegerField()),
            ],
        ),
    ]
