# Generated by Django 4.1 on 2023-05-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0012_internals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentsem8assignmentuploadmodel',
            name='assignmentm1',
            field=models.IntegerField(default='-'),
        ),
        migrations.AlterField(
            model_name='departmentsem8assignmentuploadmodel',
            name='assignmentm2',
            field=models.IntegerField(default='-'),
        ),
        migrations.AlterField(
            model_name='departmentsem8assignmentuploadmodel',
            name='assignmentm3',
            field=models.IntegerField(default='-'),
        ),
        migrations.AlterField(
            model_name='departmentsem8assignmentuploadmodel',
            name='assignmentm4',
            field=models.IntegerField(default='-'),
        ),
    ]
