# Generated by Django 4.1 on 2023-05-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0014_alter_departmentsemmarkupload_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdfsupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('pdfs', models.FileField(upload_to='bookmsapp/static')),
            ],
        ),
    ]
