# Generated by Django 4.1 on 2023-05-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0015_pdfsupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdfsuploadmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('pdfs', models.FileField(upload_to='departmentapp/static')),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='pdfsupload',
        ),
    ]
