# Generated by Django 4.1 on 2023-05-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0018_pdfsuploadmodels_delete_pdfsuploadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfsuploadmodels',
            name='pdfs',
            field=models.FileField(upload_to='static'),
        ),
    ]
