# Generated by Django 4.1 on 2023-05-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0021_attendanceuploadstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuploadstudent',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=10),
        ),
    ]
