# Generated by Django 4.1 on 2023-05-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0022_alter_attendanceuploadstudent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuploadstudent',
            name='status',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('late', 'late'), ('not uploaded', 'not uploaded')], default='not uploaded', max_length=70),
        ),
    ]
