# Generated by Django 4.1 on 2023-05-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0025_attendanceuploadstudents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfsuploadmodels',
            name='pdfs',
            field=models.FileField(upload_to='static/departmentapp'),
        ),
    ]
