# Generated by Django 4.1 on 2023-05-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0026_alter_pdfsuploadmodels_pdfs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuploadstudents',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pdfsuploadmodels',
            name='pdfs',
            field=models.FileField(upload_to='departmentapp/static'),
        ),
    ]
